version: "3"

services:
  mongo:
    image: mongo:6.0.4
    container_name: mongodb
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - ${MONGO_DB_PORT:-27017}:27017
    restart: always
  categories:
    build: back-end/services/categories/.
    container_name: categories
    environment:
      - MONGO_DB_URL=mongodb://mongodb
      - MONGO_DB_PORT=27017
      - MONGO_DB_NAME=gila-sw-db
    depends_on:
      - mongo
    ports:
      - 3000:3000
    expose:
      - 3000
  notifications:
    build: back-end/services/notifications/.
    container_name: notifications
    environment:
      - MONGO_DB_URL=mongodb://mongodb
      - MONGO_DB_PORT=27017
      - MONGO_DB_NAME=gila-sw-db
    depends_on:
      - mongo
    ports:
      - 3001:3001
    expose:
      - 3001
